config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "tasks/new", to: "tasks#new"


  get "tasks", to: "tasks#list"


  get "tasks/:id", to: "tasks#show", as: "task"
  post "tasks", to: "tasks#create"


  get "tasks/:id/edit", to: "tasks#edit", as: "task_edit"
  patch "tasks", to: "tasks#uptade"

  delete "tasks/:id", to: "tasks#destroy"


  patch "tasks/:id/done", to: "tasks#done", as: "done"
  patch "tasks/:id/undone", to: "tasks#undone", as: "undone"
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
   before_action :set_task, only: [:show, :edit, :uptade, :destroy, :done, :undone]

  def list
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
  end

  def uptade
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.delete
    redirect_to tasks_path
  end

  def done
    @task.completed = true
    @task.save
    redirect_to tasks_path
  end

  def undone
    @task.completed = false
    @task.save
    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1><%= "edit task"  %></h1>


<%= form_with model: @task do |t| %>
  <%= t.text_field :title %>
  <%= t.text_field :details %>
  <%= t.submit %>
<% end %>

app/views/tasks/list.html.erb
<h1> <%= "TASK"  %></h1>


 <ul>

    <% @tasks.each do |task| %>

       <li class="tasklist" >
        <% if task.completed %>
          <%= link_to undone_path(task), data: {turbo_method: "patch"}, class:"btn" do %>
            <i class="fa-solid fa-square-check"></i>

          <% end %>

        <% else %>
          <%= link_to done_path(task), data: {turbo_method: "patch"}, class:"btn" do %>

            <i class="fa-solid fa-square"></i>
          <% end %>

        <% end %>
        <%= link_to  "#{task.title} ",task_path(task), class:"btn"%>
        <%= link_to task_path(task), data: {turbo_method:"delete", turbo_confirm: "are you sure?"} do %>
        <i class="fa-solid fa-trash"></i>
        <% end %>
        </li>

    <% end %>


  <%=link_to "add new task", tasks_new_path %>

 </ul>

app/views/tasks/new.html.erb
<h1><%= "New task"  %></h1>


<%= form_with model: @task do |t| %>
  <%= t.text_field :title %>
  <%= t.text_field :details %>
  <%= t.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1> <%= "Show" %> </h1>
 <%= link_to "edit task", task_edit_path(@task) %>



  <li><%= "#{@task.title}, #{@task.details} " %></li>


 <%= link_to "back", tasks_path %>